/**
 * Type definitions for the Scoope API surface.
 *
 * These are hand-written for v0.1.0 and intentionally mirror the gateway's
 * TypeBox / OpenAPI schemas (see SPEC §1-§6 and `gateway/src/routes/schemas.ts`).
 *
 * In a future minor we will replace this file with types generated by
 * `openapi-typescript` against `${baseUrl}/openapi.json` — public exports
 * (`Permissions*`, `ApiKey`, `Policy`, `Escalation`, `ToolCall`, ...) will
 * remain stable so consumers do not have to migrate.
 */

// ---------- Shared primitives ----------

export type Decision = 'allow' | 'deny' | 'escalate';

export type Scope =
  | 'policy:read'
  | 'policy:write'
  | 'tool:call'
  | 'audit:read'
  | 'key:manage'
  | 'billing:read'
  | 'admin';

export type Plan = 'free' | 'starter' | 'growth' | 'enterprise';

export type EscalationStatus =
  | 'PENDING'
  | 'NOTIFIED'
  | 'APPROVED'
  | 'DENIED'
  | 'TIMED_OUT'
  | 'NOTIFIED_FAILED';

export type PolicyStatus = 'draft' | 'published' | 'archived';

export type TimeoutAction = 'auto_approve' | 'auto_deny';

export interface Page<T> {
  data: T[];
  next_cursor: string | null;
}

export interface PageQuery {
  limit?: number;
  cursor?: string;
}

// ---------- Permissions (the landing-page contract) ----------

/**
 * The shape of `scoope.permissions.check({...})` from the landing-page mockup.
 *
 * `subject`  — who is acting   (e.g. `user_123`, `agent_<uuid>`)
 * `action`   — verb             (e.g. `execute`, `read`, `write`)
 * `resource` — what is targeted (e.g. `tool:slack.send`)
 * `context`  — free-form attributes the policy engine can reference
 */
export interface PermissionCheckRequest {
  subject: string;
  action: string;
  resource: string;
  context?: Record<string, unknown>;
}

export interface PermissionCheckResult {
  allowed: boolean;
  reason?: string;
  /** Set when the decision is `escalate` and a human approval is awaiting. */
  escalation_id?: string;
  /** ID of the policy that produced the decision (`null` if no policy matched). */
  policy_id: string | null;
  /** Stable ID for this evaluation — surface in your logs for end-to-end tracing. */
  decision_id: string;
}

// ---------- Tool calls ----------

export interface ToolCallRequest {
  tool: string;
  arguments: Record<string, unknown>;
  agent_id?: string;
  metadata?: Record<string, unknown>;
}

export interface ToolCallResponse {
  id: string;
  tool: string;
  decision: Decision;
  policy_id: string | null;
  rule_id: string | null;
  result: unknown;
  escalation_id: string | null;
  latency_ms: number;
  created_at: string;
}

/** Async-job model — see SPEC §7-Q1 option B. */
export interface JobAccepted {
  id: string;
  status: 'queued' | 'running';
  poll_url?: string;
}

export type JobStatus = 'queued' | 'running' | 'succeeded' | 'failed' | 'cancelled';

export interface Job<T = unknown> {
  id: string;
  status: JobStatus;
  result?: T;
  error?: { code: string; message: string; details?: unknown };
  created_at: string;
  updated_at: string;
}

// ---------- Policies ----------

export type PolicyCondition =
  | { op: 'always' }
  | { op: 'tool_is'; tool: string }
  | { op: 'tool_in'; tools: string[] }
  | { op: 'arg_equals'; path: string; value: unknown }
  | { op: 'arg_matches'; path: string; pattern: string }
  | { op: 'agent_is'; agent_id: string }
  | { op: 'and'; all: PolicyCondition[] }
  | { op: 'or'; any: PolicyCondition[] }
  | { op: 'not'; of: PolicyCondition };

export interface PolicyEscalationConfig {
  timeout_seconds?: number;
  timeout_action?: TimeoutAction;
  webhooks?: string[];
}

export interface PolicyRule {
  id?: string;
  description?: string;
  when: PolicyCondition;
  then: {
    decision: Decision;
    reason?: string;
    escalation?: PolicyEscalationConfig;
  };
}

export interface PolicyDefinition {
  rules: PolicyRule[];
  default?: Decision;
}

export interface Policy {
  id: string;
  tenant_id: string;
  name: string;
  version: number;
  status: PolicyStatus;
  definition: PolicyDefinition;
  created_at: string;
  updated_at: string;
}

export interface CreatePolicyRequest {
  name: string;
  definition: PolicyDefinition;
  status?: 'draft' | 'published';
}

export interface UpdatePolicyRequest {
  name?: string;
  definition?: PolicyDefinition;
  status?: PolicyStatus;
}

/** Server-Sent Event shape for `/v1/events/policies` (SPEC §7-Q2 option A). */
export interface PolicyUpdateEvent {
  event: 'updated' | 'published' | 'archived' | 'deleted' | 'created';
  policy_id: string;
  tenant_id: string;
  version?: number;
  at: string;
}

// ---------- API Keys ----------

export interface ApiKey {
  id: string;
  name: string;
  prefix: string;
  tenant_id: string;
  scopes: Scope[];
  agent_id: string | null;
  expires_at: string | null;
  last_used_at: string | null;
  revoked_at: string | null;
  created_by: string;
  created_at: string;
}

export interface ApiKeyWithSecret extends ApiKey {
  /** Plaintext secret. Returned exactly once at creation/rotation. */
  secret: string;
}

export interface CreateKeyRequest {
  name: string;
  scopes: Scope[];
  agent_id?: string;
  expires_at?: string;
}

export interface RotateKeyRequest {
  grace_period_seconds?: number;
}

// ---------- Audit ----------

export interface AuditEntry {
  id: string;
  tenant_id: string;
  timestamp: string;
  agent_id: string | null;
  tool: string | null;
  action: string;
  decision: Decision | null;
  latency_ms: number | null;
  metadata: Record<string, unknown>;
}

export interface AuditQuery extends PageQuery {
  since?: string;
  until?: string;
  agent_id?: string;
  tool?: string;
  decision?: Decision;
}

// ---------- Escalations ----------

export interface Escalation {
  id: string;
  tenant_id: string;
  agent_id: string | null;
  tool_call_id: string | null;
  policy_id: string | null;
  reason: string;
  status: EscalationStatus;
  timeout_at: string;
  timeout_action: TimeoutAction;
  resolved_by: string | null;
  resolved_at: string | null;
  resolution_note: string | null;
  created_at: string;
}

export interface ResolveEscalationRequest {
  note?: string;
}

export interface EscalationListQuery extends PageQuery {
  status?: EscalationStatus;
  agent_id?: string;
}

// ---------- Usage ----------

export interface UsageMeter {
  used: number;
  limit: number | null;
}

export interface UsageReport {
  tenant_id: string;
  period_start: string;
  period_end: string;
  plan: Plan;
  tool_calls: UsageMeter;
  policy_evaluations: UsageMeter;
  escalations: UsageMeter;
  audit_queries: UsageMeter;
}

// ---------- Wire-format error body returned by the gateway ----------

export interface ApiErrorBody {
  error: string;
  message: string;
  code: string;
  details?: unknown;
}
